### ISSUE TITLE
create helm repository (using github pages)

### ISSUE THREAD

**Issue by MansM** [mechinn/pi-hole-helm#1]
I would like the repo to be able to be used as repository in argo-cd.
for this it needs to be helm compatible repository. 

Found this how to do this with github-pages
https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

**Comment by mechinn** [comment]
done, I did it slightly differently by uploading a release instead of committing the tgz to git http://mechinn.github.io/pi-hole-helm/index.yaml
